version: "3.8"

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    ports:
      - "9000:9000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - CONSUMER_THREADS=4 # Configure number of threads here
      - MAX_QUEUE_LENGTH=100 # Configure max queue length here
      - STORAGE_PATH=/app/uploads
    networks:
      - upload-network

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    volumes:
      - ./videos/Producer1:/app/videos/Producer1
      - ./videos/Producer2:/app/videos/Producer2
      - ./videos/Producer3:/app/videos/Producer3
      - ./videos/Producer4:/app/videos/Producer4
      - ./videos/Producer5:/app/videos/Producer5
    depends_on:
      - consumer
    networks:
      - upload-network
    environment:
      - SERVER_HOST=consumer
      - SERVER_PORT=9000
      - PRODUCER_THREADS=5 # Configure number of threads here

networks:
  upload-network:
    driver: bridge
